### ISSUE TITLE
Pyqaserver doesn't work with matplotlib >= 3.3.3

### ISSUE THREAD

**Issue by brjdenis** [brjdenis/qaserver#12]
Pyqaserver v2.0.1 is compatible with matplotlib v3.3.1. This must be installed manually after installing pyqaserver.
The error you get if using matplotlib >= 3.3.3:

> 'XAxis' object has no attribute '_gridOnMajor'
